Bug fix for the error wrong date format
Building with `nix-shell` or docker run without building an image
gives this error:
```
ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.4.3/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```
The jekyll issues page has suggested this fix.
https://github.com/jekyll/jekyll/issues/2938